apiVersion: v2
appVersion: stable-6865
dependencies:
- condition: prosody.enabled
  name: prosody
  repository: ""
  version: 1.2.2
description: A Helm chart for Kubernetes
name: jitsi-meet
type: application
version: 1.2.2
